### ISSUE TITLE
Your mongodb cluster is still accessible from the open internet

### ISSUE THREAD

**Issue by Sopamo** [Purvapatel4725/Blogiify-App#2]
Your commit https://github.com/Purvapatel4725/Blogiify-App/commit/7a5473c781ecb771189395679865e4af8948ee6e#diff-ba0d018cfcc74d944e838cd9e1b5c1efb1796c17f7f0c55e85353c599d6c41c7L1

is still visible via the public github search and your mongodb cluster is accessible. You might want to consider changing the password and restrict access to your cluster to only specific IPs.

**Comment by Purvapatel4725** [comment]
Thank you for the suggestion
